export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAILURE = "GET_ALL_PRODUCT_FAILURE";

export const GET_PRODUCTBYID_REQUEST = "GET_PRODUCTBYID_REQUEST";
export const GET_PRODUCTBYID_SUCCESS = "GET_PRODUCTBYID_SUCCESS";
export const GET_PRODUCTBYID_FAILURE = "GET_PRODUCTBYID_FAILURE";

export const GET_ADDTOCART_REQUEST = "GET_ADDTOCART_REQUEST";
export const GET_ADDTOCART_SUCCESS = "GET_ADDTOCART_SUCCESS";
export const GET_ADDTOCART_FAILURE = "GET_ADDTOCART_FAILURE";

export const ADD_ONE = "ADD_ONE";

export const REMOVE_ONE = "REMOVE_ONE";

export const QUANTITY = "QUANTITY";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
