export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAILURE = "GET_ALL_PRODUCT_FAILURE";

export const GET_PRODUCTBYID_REQUEST = "GET_PRODUCTBYID_REQUEST";
export const GET_PRODUCTBYID_SUCCESS = "GET_PRODUCTBYID_SUCCESS";
export const GET_PRODUCTBYID_FAILURE = "GET_PRODUCTBYID_FAILURE";
